[project]
name = "cse158-assignment2"
version = "0.1.0"
requires-python = "<3.12"
dependencies = [
    "requests",
    "python-magic",
    "implicit",
    "pandas",
]

[tool.setuptools]
py-modules = ["assignment1", "subverifier"]